#![warn(clippy::all, clippy::pedantic)]

[package]
name = "json-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
json = "0.12.4"
lazy_static = "1.5.0"
rust-fuzzy-search = "0.1.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
